# Generated by Django 5.2.5 on 2025-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instavibeapp", "0004_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_images/default.jpg", upload_to="profile_images/"
            ),
        ),
    ]
